name: Terraform

on:
  push:
     branches: [ main ]
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
    
    - name: Terraform fmt
      run: terraform init
      continue-on-error: true
