name: Terraform

on:
  push:
     branches: [ main ]
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
    
    - name: Terraform initialization
      run: terraform init
      continue-on-error: true
      
    - name: Terraform fmt
      run: terraform fmt
      continue-on-error: true
      
    - name: Terraform plan
      run: terraform plan
      continue-on-error: true
      
    - name: Terraform fmt
      run: terraform fmt
      continue-on-error: true
      
    - name: Repository secrets
      run: echo "Repository secret is :" ${{ secrets.JYOTHI }}
