name: Terraform

on:
  push:
     branches: [ main ]
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform setup
      uses: hashicorp/setup-terraform@v1
    - run: terraform 
